// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: fund/v1/fund.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FreezeAmountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FreezeAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FreezeAmountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FreezeAmountRequestMultiError, or nil if none found.
func (m *FreezeAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FreezeAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CoreOrderId

	// no validation rules for Volume

	// no validation rules for Amount

	if len(errors) > 0 {
		return FreezeAmountRequestMultiError(errors)
	}

	return nil
}

// FreezeAmountRequestMultiError is an error wrapping multiple validation
// errors returned by FreezeAmountRequest.ValidateAll() if the designated
// constraints aren't met.
type FreezeAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FreezeAmountRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FreezeAmountRequestMultiError) AllErrors() []error { return m }

// FreezeAmountRequestValidationError is the validation error returned by
// FreezeAmountRequest.Validate if the designated constraints aren't met.
type FreezeAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FreezeAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FreezeAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FreezeAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FreezeAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FreezeAmountRequestValidationError) ErrorName() string {
	return "FreezeAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FreezeAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFreezeAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FreezeAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FreezeAmountRequestValidationError{}

// Validate checks the field values on FreezeAmountResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FreezeAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FreezeAmountResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FreezeAmountResponseMultiError, or nil if none found.
func (m *FreezeAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FreezeAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FreezeAmountResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FreezeAmountResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FreezeAmountResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FreezeAmountResponseMultiError(errors)
	}

	return nil
}

// FreezeAmountResponseMultiError is an error wrapping multiple validation
// errors returned by FreezeAmountResponse.ValidateAll() if the designated
// constraints aren't met.
type FreezeAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FreezeAmountResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FreezeAmountResponseMultiError) AllErrors() []error { return m }

// FreezeAmountResponseValidationError is the validation error returned by
// FreezeAmountResponse.Validate if the designated constraints aren't met.
type FreezeAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FreezeAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FreezeAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FreezeAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FreezeAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FreezeAmountResponseValidationError) ErrorName() string {
	return "FreezeAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FreezeAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFreezeAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FreezeAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FreezeAmountResponseValidationError{}

// Validate checks the field values on FreezeAmountResponse_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FreezeAmountResponse_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FreezeAmountResponse_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FreezeAmountResponse_DataMultiError, or nil if none found.
func (m *FreezeAmountResponse_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *FreezeAmountResponse_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Commission

	// no validation rules for Digit

	if len(errors) > 0 {
		return FreezeAmountResponse_DataMultiError(errors)
	}

	return nil
}

// FreezeAmountResponse_DataMultiError is an error wrapping multiple validation
// errors returned by FreezeAmountResponse_Data.ValidateAll() if the
// designated constraints aren't met.
type FreezeAmountResponse_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FreezeAmountResponse_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FreezeAmountResponse_DataMultiError) AllErrors() []error { return m }

// FreezeAmountResponse_DataValidationError is the validation error returned by
// FreezeAmountResponse_Data.Validate if the designated constraints aren't met.
type FreezeAmountResponse_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FreezeAmountResponse_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FreezeAmountResponse_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FreezeAmountResponse_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FreezeAmountResponse_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FreezeAmountResponse_DataValidationError) ErrorName() string {
	return "FreezeAmountResponse_DataValidationError"
}

// Error satisfies the builtin error interface
func (e FreezeAmountResponse_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFreezeAmountResponse_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FreezeAmountResponse_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FreezeAmountResponse_DataValidationError{}
