// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.0
// source: fund/v1/fund.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FundService_FreezeAmount_FullMethodName = "/FundService/FreezeAmount"
)

// FundServiceClient is the client API for FundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FundServiceClient interface {
	FreezeAmount(ctx context.Context, in *FreezeAmountRequest, opts ...grpc.CallOption) (*FreezeAmountResponse, error)
}

type fundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFundServiceClient(cc grpc.ClientConnInterface) FundServiceClient {
	return &fundServiceClient{cc}
}

func (c *fundServiceClient) FreezeAmount(ctx context.Context, in *FreezeAmountRequest, opts ...grpc.CallOption) (*FreezeAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeAmountResponse)
	err := c.cc.Invoke(ctx, FundService_FreezeAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundServiceServer is the server API for FundService service.
// All implementations must embed UnimplementedFundServiceServer
// for forward compatibility.
type FundServiceServer interface {
	FreezeAmount(context.Context, *FreezeAmountRequest) (*FreezeAmountResponse, error)
	mustEmbedUnimplementedFundServiceServer()
}

// UnimplementedFundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFundServiceServer struct{}

func (UnimplementedFundServiceServer) FreezeAmount(context.Context, *FreezeAmountRequest) (*FreezeAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreezeAmount not implemented")
}
func (UnimplementedFundServiceServer) mustEmbedUnimplementedFundServiceServer() {}
func (UnimplementedFundServiceServer) testEmbeddedByValue()                     {}

// UnsafeFundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FundServiceServer will
// result in compilation errors.
type UnsafeFundServiceServer interface {
	mustEmbedUnimplementedFundServiceServer()
}

func RegisterFundServiceServer(s grpc.ServiceRegistrar, srv FundServiceServer) {
	// If the following call pancis, it indicates UnimplementedFundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FundService_ServiceDesc, srv)
}

func _FundService_FreezeAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).FreezeAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_FreezeAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).FreezeAmount(ctx, req.(*FreezeAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FundService_ServiceDesc is the grpc.ServiceDesc for FundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FundService",
	HandlerType: (*FundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FreezeAmount",
			Handler:    _FundService_FreezeAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fund/v1/fund.proto",
}
