// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.26.0
// source: fund/v1/fund.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFundServiceFreezeAmount = "/FundService/FreezeAmount"

type FundServiceHTTPServer interface {
	FreezeAmount(context.Context, *FreezeAmountRequest) (*FreezeAmountResponse, error)
}

func RegisterFundServiceHTTPServer(s *http.Server, srv FundServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/fund/freezeamount", _FundService_FreezeAmount0_HTTP_Handler(srv))
}

func _FundService_FreezeAmount0_HTTP_Handler(srv FundServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FreezeAmountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFundServiceFreezeAmount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FreezeAmount(ctx, req.(*FreezeAmountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FreezeAmountResponse)
		return ctx.Result(200, reply)
	}
}

type FundServiceHTTPClient interface {
	FreezeAmount(ctx context.Context, req *FreezeAmountRequest, opts ...http.CallOption) (rsp *FreezeAmountResponse, err error)
}

type FundServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewFundServiceHTTPClient(client *http.Client) FundServiceHTTPClient {
	return &FundServiceHTTPClientImpl{client}
}

func (c *FundServiceHTTPClientImpl) FreezeAmount(ctx context.Context, in *FreezeAmountRequest, opts ...http.CallOption) (*FreezeAmountResponse, error) {
	var out FreezeAmountResponse
	pattern := "/v1/fund/freezeamount"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFundServiceFreezeAmount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
